import type { CharacterProfile, Contact } from './types';

type ProfileSeed = Omit<CharacterProfile, 'unlocked'>;

const PROFILE_SEEDS: ProfileSeed[] = [
  {
    id: 'lowe',
    name: 'Lowe',
    displayName: 'Lowe Moss',
    status: 'Online agora',
    phone: '+55 78-097',
    pronouns: 'He / Him',
    zodiac: 'Escorpião',
    zodiacSymbol: '♏',
    bio: '?',
    link: '',
    avatarKey: 'lowe',
    bannerKey: 'cover_20',
    mediaKeys: [
      'lowe_media_15',
      'lowe_media_14',
      'lowe_media_13',
      'lowe_media_12',
      'lowe_media_11',
      'lowe_media_10',
      'lowe_media_09',
      'lowe_media_08',
      'lowe_media_07',
      'lowe_media_06',
      'lowe_media_05',
      'lowe_media_04',
      'lowe_media_03',
      'lowe_media_02',
      'lowe_media_01',
    ],
  },
  {
    id: 'liv',
    name: 'Liv',
    displayName: 'Olivia Harper',
    status: 'Online agora',
    phone: '+55 32-618',
    pronouns: 'She / Her',
    zodiac: 'Câncer',
    zodiacSymbol: '♋',
    bio: 'Leia para uma criança 💖📖',
    link: '',
    avatarKey: 'liv',
    bannerKey: 'liv_banner',
    mediaKeys: [
      'liv_media_14',
      'liv_media_13',
      'liv_media_12',
      'liv_media_11',
      'liv_media_10',
      'liv_media_09',
      'liv_media_08',
      'liv_media_07',
      'liv_media_06',
      'liv_media_05',
      'liv_media_04',
      'liv_media_03',
      'liv_media_02',
      'liv_media_01',
    ],
  },
  {
    id: 'luke',
    name: 'Luke',
    displayName: 'Luke Hart',
    status: 'Offline',
    phone: '+55 21-520',
    pronouns: 'He / Him',
    zodiac: 'Áries',
    zodiacSymbol: '♈',
    bio: 'Perfil bloqueado por enquanto.',
    link: '',
    avatarKey: 'luke',
    bannerKey: 'luke_banner',
    mediaKeys: [],
  },
  {
    id: 'olivia',
    name: 'Olivia',
    displayName: 'Olivia Reyes',
    status: 'Offline',
    phone: '+55 09-764',
    pronouns: 'She / Her',
    zodiac: 'Libra',
    zodiacSymbol: '♎',
    bio: 'Perfil bloqueado por enquanto.',
    link: '',
    avatarKey: 'olivia',
    bannerKey: 'olivia_banner',
    mediaKeys: [],
  },
  {
    id: 'scar',
    name: 'Scarlett',
    displayName: 'Scarlett Vale',
    status: 'Offline',
    phone: '+55 89-155',
    pronouns: 'They / Them',
    zodiac: 'Capricórnio',
    zodiacSymbol: '♑',
    bio: 'Perfil bloqueado por enquanto.',
    link: '',
    avatarKey: 'scar',
    bannerKey: 'scar_banner',
    mediaKeys: [],
  },
  {
    id: 'ruby',
    name: 'Ruby',
    displayName: 'Ruby Moss',
    status: 'Desaparecida',
    phone: '+55 44-319',
    pronouns: 'She / Her',
    zodiac: 'Peixes',
    zodiacSymbol: '♓',
    bio: 'Desaparecida. Último contato: o caderno e o pendrive.',
    link: '',
    avatarKey: 'ruby',
    bannerKey: 'ruby_banner',
    mediaKeys: [],
  },
];

export const CONTACTS: Contact[] = PROFILE_SEEDS.map((p) => ({
  id: p.id,
  name: p.name,
  status: p.status,
  avatarKey: p.avatarKey,
  phone: p.phone,
  unlocked: p.id === 'lowe' || p.id === 'liv',
}));

export function getProfileSeed(contactId: string): ProfileSeed | undefined {
  return PROFILE_SEEDS.find((p) => p.id === contactId);
}

export function buildCharacterProfile(
  contactId: string,
  unlocked: boolean,
): CharacterProfile | null {
  const seed = getProfileSeed(contactId);
  if (!seed) return null;
  return { ...seed, unlocked };
}
